apiVersion: v1
kind: Pod
metadata:
  name: demo-vulnerable
spec:
  hostNetwork: true
  hostPID: true
  automountServiceAccountToken: true
  containers:
    - name: app
      image: nginx:latest
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        readOnlyRootFilesystem: false
        capabilities:
          add:
            - SYS_ADMIN
