"""
plugins/mysql/rules.py — GENERATED by `ccss plugin add`.

Deterministic SystemProfile inference. Edit the AV/Au logic for this service.
"""

from __future__ import annotations

from core.models import AuValue, AVValue, Directive, SystemProfile


def _infer_av(directives: list[Directive]) -> tuple[AVValue, str]:
    bind_dirs = [d for d in directives if d.name == "bind-address"]
    if not bind_dirs:
        return "N", "No bind-address; service defaults to network exposure"
    values = [d.value.strip() for d in bind_dirs]
    loopback = ("127.", "::1", "localhost", "[::1]")
    all_loopback = all(
        any(v.lower().strip("[]").startswith(p) or v.lower().strip("[]") == p for p in loopback)
        for v in values
    )
    if all_loopback:
        return "L", f"All bind-address entries bound to loopback only: {values}"
    return "N", f"At least one bind-address exposes a non-loopback address: {values}"


def _infer_au(directives: list[Directive]) -> tuple[AuValue, str]:
    # Default: Au=None (safe default — most service misconfigs are exploitable
    # without valid credentials). Edit if this service authenticates first.
    return "N", "Au=None (default; edit for MySQL)"


def infer_profile(directives: list[Directive]) -> SystemProfile:
    av, rationale_av = _infer_av(directives)
    au, rationale_au = _infer_au(directives)
    return SystemProfile(av=av, au=au, rationale_av=rationale_av, rationale_au=rationale_au)
