"""
plugins/redis/__init__.py — GENERATED by `ccss plugin add`.

Edit this file to customise detection and metadata for Redis.
"""

from __future__ import annotations

from pathlib import Path

from config_assessment.core.models import Directive, SystemProfile, TargetMetadata
from config_assessment.core.runtime import register_plugin
from config_assessment.core.target import (
    Target,
    CONFIDENCE_EXACT_FILENAME,
    CONFIDENCE_SYNTAX_MARKER,
    CONFIDENCE_DIRECTORY,
)
from config_assessment.plugins.redis.parser import parse_file
from config_assessment.plugins.redis.rules import infer_profile

_FILENAMES = {'redis.conf'}


class RedisPlugin(Target):
    """Redis target plugin (U Redis Enterprise 6-x STIG V2R2 Manual-xccdf)."""

    def detect(self, path: str) -> bool:
        p = Path(path)
        if p.is_file():
            return p.name in _FILENAMES
        if p.is_dir():
            return any((p / fn).exists() for fn in _FILENAMES)
        return False

    def parse_config(self, path: str) -> list[Directive]:
        p = Path(path)
        if p.is_dir():
            for fn in _FILENAMES:
                entry = p / fn
                if entry.exists():
                    return parse_file(str(entry))
            return []
        return parse_file(path)

    def get_profile(self, directives: list[Directive]) -> SystemProfile:
        return infer_profile(directives)

    def metadata(self) -> TargetMetadata:
        return TargetMetadata(
            name="redis",
            display_name="Redis",
            version="1.0",
            benchmark_source="U Redis Enterprise 6-x STIG V2R2 Manual-xccdf",
            priority=100,
            version_exposing_directives=(),
        )

    def detection_confidence(self, path: str) -> int:
        p = Path(path)
        if p.is_file() and p.name in _FILENAMES:
            return CONFIDENCE_EXACT_FILENAME
        if p.is_dir():
            return CONFIDENCE_DIRECTORY
        return 0


register_plugin(RedisPlugin())
