"""
plugins/redis/build_redis.py — GENERATED by `ccss plugin add`.

Defines the ground-truth ENTRIES for Redis. Mirrors the Apache /
Nginx build modules; run via `ccss build --target redis`.
"""

from __future__ import annotations

from config_assessment.plugins.apache_httpd.llm_pipeline import MisconfigEntry

_TARGET = "redis"

ENTRIES: list[MisconfigEntry] = [
    MisconfigEntry('/etc/opt/redislabs/permissions', '704', '700', 'SV-251226r961041_rule', "", _TARGET),
    MisconfigEntry('--askpass', '', 'None', 'SV-251228r961047_rule', "", _TARGET),
    MisconfigEntry('min_data_TLS_version', '1.0', '1.2', 'SV-251229r961050_rule', "", _TARGET),
    MisconfigEntry('fips', 'insecure_value', 'on', 'SV-251231r962034_rule', "", _TARGET),
    MisconfigEntry('encryption_method', 'insecure_value', 'LUKS', 'SV-251242r961128_rule', "", _TARGET),
    MisconfigEntry('encryption', 'insecure_value', 'LUKS', 'SV-251243r1018562_rule', "", _TARGET),
    MisconfigEntry('encryption', 'insecure_value', 'LUKS', 'SV-251244r1018563_rule', "", _TARGET),
    MisconfigEntry('version', '', 'supported_version_number', 'SV-265880r999546_rule', "", _TARGET),
    MisconfigEntry('log_level', 'insecure_value', '<organizationally defined level>', 'SV-251190r960879_rule', "", _TARGET),
    MisconfigEntry('alert_threshold_storage', 'less than 75%', '75%', 'SV-251197r961398_rule', "", _TARGET),
    MisconfigEntry('/etc/logrotate.conf', '', 'secured_configuration', 'SV-251200r960915_rule', "", _TARGET),
    MisconfigEntry('timezone', 'insecure_value', 'UTC', 'SV-251201r961443_rule', "", _TARGET),
    MisconfigEntry('/var/opt/redislabs/log/* permissions', '777', '640 or 660', 'SV-251202r960930_rule', "", _TARGET),
    MisconfigEntry('/var/opt/redislabs/log/* permissions', '777', '640 or 660', 'SV-251203r960933_rule', "", _TARGET),
    MisconfigEntry('/var/opt/redislabs/log/* permissions', '777', '640 or 660', 'SV-251204r960936_rule', "", _TARGET),
    MisconfigEntry('user owner', 'insecure_value', 'redislabs', 'SV-251205r960939_rule', "", _TARGET),
    MisconfigEntry('user owner', 'insecure_value', 'redislabs', 'SV-251206r960942_rule', "", _TARGET),
    MisconfigEntry('directory_permissions', '701', '700', 'SV-251207r960945_rule', "", _TARGET),
    MisconfigEntry('user_role', 'viewer', 'appropriate_for_function', 'SV-251209r961461_rule', "", _TARGET),
    MisconfigEntry('installation_user', 'insecure_value', 'appropriate_people', 'SV-251211r960960_rule', "", _TARGET),
    MisconfigEntry('/var/opt/redislabs', '', '/mnt/dedicated_redis_directory', 'SV-251212r960960_rule', "", _TARGET),
    MisconfigEntry('default database access', 'enabled', 'disabled', 'SV-251222r960969_rule', "", _TARGET),
    MisconfigEntry('password_hashing_method', 'insecure_value', 'one-way, salted hashing functions (e.g., SHA256)', 'SV-251223r1018619_rule', "", _TARGET),
    MisconfigEntry('cm_session_timeout_minutes', '15', '<organizationally_defined_value>', 'SV-251224r961521_rule', "", _TARGET),
    MisconfigEntry('default_database_access', 'checked', 'unchecked', 'SV-251230r961053_rule', "", _TARGET),
    MisconfigEntry('fips_mode', 'insecure_value', 'on', 'SV-251232r961857_rule', "", _TARGET),
    MisconfigEntry('fips', 'insecure_value', 'on', 'SV-251233r961857_rule', "", _TARGET),
    MisconfigEntry('/proc/sys/crypto/fips_enabled', '0', '1', 'SV-251234r961857_rule', "", _TARGET),
    MisconfigEntry('tls_version', '< v1.2', '>= 1.2', 'SV-251237r961116_rule', "", _TARGET),
    MisconfigEntry('certificate', 'insecure_value', 'certificate issued by DoD PKI or DoD-approved PKI Certification Authorities (CAs)', 'SV-251239r961596_rule', "", _TARGET),
    MisconfigEntry('persistence', 'insecure_value', 'Append Only File (AOF) - fsync every write', 'SV-251240r961122_rule', "", _TARGET),
    MisconfigEntry('UMASK', '022', '077', 'SV-251247r961149_rule', "", _TARGET),
    MisconfigEntry('lua_scripts_enabled', 'true', 'false', 'SV-251250r961158_rule', "", _TARGET),
    MisconfigEntry('lua_scripts_enabled', 'true', 'false', 'SV-251251r961158_rule', "", _TARGET),
    MisconfigEntry('max_connections', '10k', '<number_of_connections>', 'SV-251183r960735_rule', "", _TARGET),
]
