"""
plugins/redis/build_redis.py — GENERATED by `ccss plugin add`.

Defines the ground-truth ENTRIES for Redis. Mirrors the Apache /
Nginx build modules; run via `ccss build --target redis`.
"""

from __future__ import annotations

from config_assessment.plugins.apache_httpd.llm_pipeline import MisconfigEntry

_TARGET = "redis"

ENTRIES: list[MisconfigEntry] = [
    MisconfigEntry('chown', '', 'redislabs:redislabs', 'SV-251226r961041_rule', "", _TARGET),
    MisconfigEntry('chown', '*:*', 'redislabs:redislabs', 'SV-251205r960939_rule', "", _TARGET),
    MisconfigEntry('permissions', 'more than 700', '700', 'SV-251206r960942_rule', "", _TARGET),
    MisconfigEntry('chown', '', 'redislabs:redislabs /var/opt/redislabs/log', 'SV-251207r960945_rule', "", _TARGET),
    MisconfigEntry('Default database access', 'enabled', 'disabled', 'SV-251222r960969_rule', "", _TARGET),
    MisconfigEntry('default database access', 'checked', 'unchecked', 'SV-251230r961053_rule', "", _TARGET),
    MisconfigEntry('/proc/sys/crypto/fips_enabled', '0', '1', 'SV-251234r961857_rule', "", _TARGET),
    MisconfigEntry('disabled_commands', 'EVAL,EVALSHA', '', 'SV-251250r961158_rule', "", _TARGET),
    MisconfigEntry('disabled_commands', 'EVAL,EVALSHA', '', 'SV-251251r961158_rule', "", _TARGET),
    MisconfigEntry('max_connections', '', '<number_of_connections>', 'SV-251183r960735_rule', "", _TARGET),
]
