"""
plugins/redis/rules.py — GENERATED by `ccss plugin add`.

Deterministic SystemProfile inference. Edit the AV/Au logic for this service.
"""

from __future__ import annotations

from config_assessment.core.models import AuValue, AVValue, Directive, SystemProfile


# Absence rules: a directive that MUST be present/enabled. Flagged as a
# misconfiguration when missing from the scanned config (bad_value="").
ABSENCE_RULES: list[dict] = [
    {"directive": 'saslauthd configuration', "good_value": 'imported and correctly configured', "required_when": "always", "cis_section": 'SV-251184r960768_rule'},
    {"directive": 'Redis ACL roles', "good_value": 'appropriate role', "required_when": "always", "cis_section": 'SV-251185r960792_rule'},
    {"directive": 'role_assignment', "good_value": 'organizationally defined policy', "required_when": "always", "cis_section": 'SV-251186r961317_rule'},
    {"directive": 'name', "good_value": 'Redis ACL rule', "required_when": "always", "cis_section": 'SV-251187r961317_rule'},
    {"directive": 'role', "good_value": 'viewer (for users without the need to modify the database) or custom role with appropriate permissions (for users with access to databases)', "required_when": "always", "cis_section": 'SV-251188r961353_rule'},
    {"directive": 'Redis Modules', "good_value": 'None', "required_when": "always", "cis_section": 'SV-251189r961359_rule'},
    {"directive": 'acl_permissions', "good_value": 'defined and configured with appropriate permissions and privileges as defined by the organization', "required_when": "always", "cis_section": 'SV-251191r960882_rule'},
    {"directive": '/etc/audit/audit.rules', "good_value": '[{"action": "always", "event": "exit", "path": "/opt/redislabs/bin/redis-cli", "perm": "x", "auid":">=1000", "auid":"!=unset", "key": "privileged-priv_change"}, {"action": "always", "event": "exit", "path": "/opt/redislabs/bin/rladmin", "perm": "x", "auid":">=1000", "auid":"!=unset", "key": "privileged-priv_change"}]', "required_when": "always", "cis_section": 'SV-251192r961839_rule'},
    {"directive": 'storage', "good_value": '<organization-defined_value>', "required_when": "always", "cis_section": 'SV-251195r961392_rule'},
    {"directive": '/etc/rsyslog.d/redislabs.conf', "good_value": '', "required_when": "always", "cis_section": 'SV-251196r961860_rule'},
    {"directive": 'user_permissions', "good_value": 'appropriate_role', "required_when": "always", "cis_section": 'SV-251208r1018617_rule'},
    {"directive": 'user_ownership', "good_value": 'appropriate_user', "required_when": "always", "cis_section": 'SV-251210r960960_rule'},
    {"directive": 'security configuration settings', "good_value": 'DoD security configuration and implementation guidance, including STIGs, NSA configuration guides, CTOs, DTMs, and IAVMs', "required_when": "always", "cis_section": 'SV-251214r961863_rule'},
    {"directive": 'unauthorized_ports', "good_value": '[1968]', "required_when": "always", "cis_section": 'SV-251215r961470_rule'},
    {"directive": 'Redis modules', "good_value": 'secure_value', "required_when": "always", "cis_section": 'SV-251217r960963_rule'},
    {"directive": 'Redis modules', "good_value": 'unused components should be removed', "required_when": "always", "cis_section": 'SV-251218r960963_rule'},
    {"directive": 'Redis modules', "good_value": 'Secure modules only approved by ISSO', "required_when": "always", "cis_section": 'SV-251219r960963_rule'},
    {"directive": 'unauthorized_ports', "good_value": '[1968]', "required_when": "always", "cis_section": 'SV-251220r960966_rule'},
    {"directive": 'certificate', "good_value": 'RS server default certificates and key replaced with CA-signed certificate', "required_when": "always", "cis_section": 'SV-251225r961038_rule'},
    {"directive": 'ldap_auth', "good_value": 'enabled', "required_when": "always", "cis_section": 'SV-251227r961044_rule'},
    {"directive": 'tls', "good_value": 'present', "required_when": "always", "cis_section": 'SV-251238r961119_rule'},
    {"directive": 'Persistence', "good_value": '', "required_when": "always", "cis_section": 'SV-251241r961125_rule'},
    {"directive": 'tls', "good_value": 'organizationally defined CA-signed certificates', "required_when": "always", "cis_section": 'SV-251248r961638_rule'},
    {"directive": 'tls', "good_value": 'secured', "required_when": "always", "cis_section": 'SV-251249r961641_rule'},
    {"directive": 'Redis version', "good_value": 'v6.0, v5.6, v5.4, v5.2', "required_when": "always", "cis_section": 'SV-251253r1001008_rule'},
    {"directive": 'ldap_servers', "good_value": "[{'host': 'ldap.example.com', 'port': 636}]", "required_when": "always", "cis_section": 'SV-251428r1018620_rule'},
    {"directive": '/opt/redislabs', "good_value": '', "required_when": "always", "cis_section": 'SV-251252r961677_rule'},
]


def _infer_av(directives: list[Directive]) -> tuple[AVValue, str]:
    return "N", "Network service (no bind directive declared)"


def _infer_au(directives: list[Directive]) -> tuple[AuValue, str]:
    # Default: Au=None (safe default — most service misconfigs are exploitable
    # without valid credentials). Edit if this service authenticates first.
    return "N", "Au=None (default; edit for Redis)"


def infer_profile(directives: list[Directive]) -> SystemProfile:
    av, rationale_av = _infer_av(directives)
    au, rationale_au = _infer_au(directives)
    return SystemProfile(av=av, au=au, rationale_av=rationale_av, rationale_au=rationale_au)
