"""
plugins/redis/rules.py — GENERATED by `ccss plugin add`.

Deterministic SystemProfile inference. Edit the AV/Au logic for this service.
"""

from __future__ import annotations

from config_assessment.core.models import AuValue, AVValue, Directive, SystemProfile


# Absence rules: a directive that MUST be present/enabled. Flagged as a
# misconfiguration when missing from the scanned config (bad_value="").
ABSENCE_RULES: list[dict] = [
    {"directive": 'min_data_TLS_version', "good_value": '1.2', "required_when": "always", "cis_section": 'SV-251229r961050_rule'},
    {"directive": 'fips', "good_value": '1', "required_when": "always", "cis_section": 'SV-251231r962034_rule'},
    {"directive": '/etc/audit/audit.rules', "good_value": '', "required_when": "always", "cis_section": 'SV-251192r961839_rule'},
    {"directive": 'redislabs.conf', "good_value": '/etc/rsyslog.d/redislabs.conf', "required_when": "always", "cis_section": 'SV-251196r961860_rule'},
    {"directive": 'Alerts', "good_value": 'enabled for storage volume reaching 75 percent', "required_when": "always", "cis_section": 'SV-251197r961398_rule'},
    {"directive": 'cm_session_timeout_minutes', "good_value": '<value_to_enter>', "required_when": "always", "cis_section": 'SV-251224r961521_rule'},
    {"directive": 'fips', "good_value": '1', "required_when": "always", "cis_section": 'SV-251232r961857_rule'},
    {"directive": 'fips', "good_value": '1', "required_when": "always", "cis_section": 'SV-251233r961857_rule'},
    {"directive": 'TLS', "good_value": 'path_to_client_certificate', "required_when": "always", "cis_section": 'SV-251238r961119_rule'},
    {"directive": 'Persistence', "good_value": 'Append Only File (AOF) - fsync every write', "required_when": "always", "cis_section": 'SV-251240r961122_rule'},
    {"directive": 'Persistence', "good_value": 'enabled', "required_when": "always", "cis_section": 'SV-251241r961125_rule'},
    {"directive": 'UMASK', "good_value": '077', "required_when": "always", "cis_section": 'SV-251247r961149_rule'},
    {"directive": 'TLS', "good_value": 'contents of client certificate', "required_when": "always", "cis_section": 'SV-251249r961641_rule'},
]


def _infer_av(directives: list[Directive]) -> tuple[AVValue, str]:
    return "N", "Network service (no bind directive declared)"


def _infer_au(directives: list[Directive]) -> tuple[AuValue, str]:
    # Default: Au=None (safe default — most service misconfigs are exploitable
    # without valid credentials). Edit if this service authenticates first.
    return "N", "Au=None (default; edit for Redis)"


def infer_profile(directives: list[Directive]) -> SystemProfile:
    av, rationale_av = _infer_av(directives)
    au, rationale_au = _infer_au(directives)
    return SystemProfile(av=av, au=au, rationale_av=rationale_av, rationale_au=rationale_au)
