-- core/db/schema.sql
-- ==================
-- CCSS-Scan Framework — database schema (SQLite compatible)

CREATE TABLE IF NOT EXISTS targets (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    name             TEXT    NOT NULL UNIQUE,
    display_name     TEXT    NOT NULL,
    version          TEXT    NOT NULL,
    benchmark_source TEXT    NOT NULL,
    created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS misconfigurations (
    id               TEXT    PRIMARY KEY,
    target_id        INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
    target_name      TEXT    NOT NULL,
    directive        TEXT    NOT NULL,
    bad_value        TEXT    NOT NULL,
    good_value       TEXT    NOT NULL DEFAULT '',
    av               TEXT    NOT NULL DEFAULT 'N',
    au               TEXT    NOT NULL DEFAULT 'N',
    ac               TEXT    NOT NULL,
    c                TEXT    NOT NULL,
    i                TEXT    NOT NULL,
    a                TEXT    NOT NULL,
    base_score       REAL    NOT NULL DEFAULT 0.0,
    temporal_score   REAL    NOT NULL DEFAULT 0.0,
    gel              TEXT    NOT NULL DEFAULT 'ND',
    grl              TEXT    NOT NULL DEFAULT 'ND',
    cves             TEXT    NOT NULL DEFAULT '[]',
    cce_id           TEXT    NOT NULL DEFAULT '',
    cis_section      TEXT    NOT NULL DEFAULT '',
    justification    TEXT    NOT NULL DEFAULT '',
    recommendation   TEXT    NOT NULL DEFAULT '',

    -- Absence detection fields (Phase 1 extension).
    -- rule_type = 'value' (lookup by bad_value) | 'absence' (directive missing)
    -- required_when = 'always' | 'if_directive:<name>' (conditional firing)
    -- expected_value_prefix: for multi-instance directives (e.g. add_header),
    --   the value prefix that must be present; '' means pure directive absence.
    rule_type             TEXT    NOT NULL DEFAULT 'value',
    required_when         TEXT    NOT NULL DEFAULT 'always',
    expected_value_prefix TEXT    NOT NULL DEFAULT '',

    -- Stage 3: rich narrative generated by LLM at build time.
    -- JSON object with fields:
    --   description: str
    --   potential_impact: list[str]
    --   exploitation_scenario: {prerequisites: list[str], example: str, result: str}
    --   metric_justifications: {ac, c, i, a, gel, grl: str}
    --   (av and au justifications are generated at runtime by the rule engine)
    narrative        TEXT    NOT NULL DEFAULT '{}',

    created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (target_name, directive, bad_value, expected_value_prefix)
);

CREATE INDEX IF NOT EXISTS idx_misconf_lookup
    ON misconfigurations (target_name, directive, bad_value);

CREATE INDEX IF NOT EXISTS idx_misconf_target
    ON misconfigurations (target_name);

-- Migration helper: add narrative column to existing databases
-- (SQLite ignores ADD COLUMN if it already exists via IF NOT EXISTS workaround)
-- The database.py migration method handles this at startup.

CREATE TABLE IF NOT EXISTS attack_chains (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    target_id            INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
    target_name          TEXT    NOT NULL,
    chain_id             TEXT    NOT NULL,
    misconfig_directives TEXT    NOT NULL DEFAULT '[]',
    amplification        REAL    NOT NULL DEFAULT 1.0,
    justification        TEXT    NOT NULL DEFAULT '',
    cross_target         INTEGER NOT NULL DEFAULT 0,
    created_at           TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (target_name, chain_id)
);

CREATE INDEX IF NOT EXISTS idx_chains_target
    ON attack_chains (target_name);

CREATE TABLE IF NOT EXISTS scan_results (
    id                      TEXT    PRIMARY KEY,
    target_name             TEXT    NOT NULL,
    input_path              TEXT    NOT NULL,
    input_hash              TEXT    NOT NULL,
    profile_av              TEXT    NOT NULL,
    profile_au              TEXT    NOT NULL,
    global_base_score       REAL    NOT NULL DEFAULT 0.0,
    global_temporal_score   REAL    NOT NULL DEFAULT 0.0,
    severity                TEXT    NOT NULL DEFAULT 'None',
    total_directives        INTEGER NOT NULL DEFAULT 0,
    total_issues            INTEGER NOT NULL DEFAULT 0,
    total_chains            INTEGER NOT NULL DEFAULT 0,
    issues_json             TEXT    NOT NULL DEFAULT '[]',
    chains_json             TEXT    NOT NULL DEFAULT '[]',
    timestamp               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_scan_results_target
    ON scan_results (target_name);

CREATE INDEX IF NOT EXISTS idx_scan_results_hash
    ON scan_results (input_hash);
