"""
plugins/postgresql/build_postgresql.py — GENERATED by `ccss plugin add`.

Defines the ground-truth ENTRIES for PostgreSQL. Mirrors the Apache /
Nginx build modules; run via `ccss build --target postgresql`.
"""

from __future__ import annotations

from config_assessment.plugins.apache_httpd.llm_pipeline import MisconfigEntry

_TARGET = "postgresql"

ENTRIES: list[MisconfigEntry] = [
    MisconfigEntry('syslog_facility', 'LOCAL0', 'LOCAL1', '3.1.10', "", _TARGET),
    MisconfigEntry('syslog_sequence_numbers', '', 'on', '3.1.11', "", _TARGET),
    MisconfigEntry('syslog_split_messages', '', 'on', '3.1.12', "", _TARGET),
    MisconfigEntry('syslog_ident', 'postgres', 'proddb', '3.1.13', "", _TARGET),
    MisconfigEntry('log_min_messages', '', 'warning', '3.1.14', "", _TARGET),
    MisconfigEntry('log_min_error_statement', '', 'error', '3.1.15', "", _TARGET),
    MisconfigEntry('debug_print_parse', '', 'off', '3.1.16', "", _TARGET),
    MisconfigEntry('debug_print_rewritten', 'on', 'off', '3.1.17', "", _TARGET),
    MisconfigEntry('debug_print_plan', 'on', 'off', '3.1.18', "", _TARGET),
    MisconfigEntry('debug_pretty_print', '', 'on', '3.1.19', "", _TARGET),
    MisconfigEntry('log_destination', 'stderr', 'csvlog', '3.1.2', "", _TARGET),
    MisconfigEntry('log_disconnections', '', 'on', '3.1.21', "", _TARGET),
    MisconfigEntry('log_hostname', '', 'off', '3.1.23', "", _TARGET),
    MisconfigEntry('log_line_prefix', '%m [%p]', '%m [%p]: [%%l-1] db=%%d,user=%%u,app=%%a,client=%%h', '3.1.24', "", _TARGET),
    MisconfigEntry('log_statement', 'none', 'ddl', '3.1.25', "", _TARGET),
    MisconfigEntry('log_timezone', '', 'GMT', '3.1.26', "", _TARGET),
    MisconfigEntry('log_directory', '.', '/var/log/postgres', '3.1.4', "", _TARGET),
    MisconfigEntry('log_filename', 'postgresql-%a.log', 'postgresql-%Y%m%d.log', '3.1.5', "", _TARGET),
    MisconfigEntry('log_truncate_on_rotation', '', 'on', '3.1.7', "", _TARGET),
    MisconfigEntry('log_rotation_age', '1d', '1h', '3.1.8', "", _TARGET),
    MisconfigEntry('log_rotation_size', '0', '1GB', '3.1.9', "", _TARGET),
    MisconfigEntry('WITH PASSWORD option in CREATE ROLE or ALTER ROLE', '', 'specified', '4.10', "", _TARGET),
    MisconfigEntry('listen_addresses', '', '<your IP>', '5.2', "", _TARGET),
    MisconfigEntry('ALTER USER <dbuser> CONNECTION LIMIT', '-1', '<reasonable concurrent connection count>', '5.5', "", _TARGET),
    MisconfigEntry('ssl_ciphers', '', 'TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_128_CCM_SHA256', '6.10', "", _TARGET),
    MisconfigEntry('ssl_min_protocol_version', 'TLSv1.0', 'TLSv1.2', '6.9', "", _TARGET),
]
