"""
plugins/postgresql/rules.py — GENERATED by `ccss plugin add`.

Deterministic SystemProfile inference. Edit the AV/Au logic for this service.
"""

from __future__ import annotations

from config_assessment.core.models import AuValue, AVValue, Directive, SystemProfile


# Absence rules: a directive that MUST be present/enabled. Flagged as a
# misconfiguration when missing from the scanned config (bad_value="").
ABSENCE_RULES: list[dict] = [
    {"directive": 'log_connections', "good_value": 'on', "required_when": "always", "cis_section": '3.1.20'},
    {"directive": 'pgaudit', "good_value": 'on', "required_when": "always", "cis_section": '3.2'},
    {"directive": 'pgcrypto extension', "good_value": 'CREATE EXTENSION pgcrypto;', "required_when": "always", "cis_section": '6.11'},
    {"directive": 'fips-mode-setup --enable', "good_value": '--enable', "required_when": "always", "cis_section": '6.7'},
    {"directive": 'replication_user_creation', "good_value": "create user replication_user REPLICATION encrypted password 'XXX';", "required_when": "always", "cis_section": '7.1'},
    {"directive": 'log_replication_commands', "good_value": 'on', "required_when": "always", "cis_section": '7.2'},
]


def _infer_av(directives: list[Directive]) -> tuple[AVValue, str]:
    bind_dirs = [d for d in directives if d.name == "listen_addresses"]
    if not bind_dirs:
        return "N", "No listen_addresses; service defaults to network exposure"
    values = [d.value.strip() for d in bind_dirs]
    loopback = ("127.", "::1", "localhost", "[::1]")
    all_loopback = all(
        any(v.lower().strip("[]").startswith(p) or v.lower().strip("[]") == p for p in loopback)
        for v in values
    )
    if all_loopback:
        return "L", f"All listen_addresses entries bound to loopback only: {values}"
    return "N", f"At least one listen_addresses exposes a non-loopback address: {values}"


def _infer_au(directives: list[Directive]) -> tuple[AuValue, str]:
    # Default: Au=None (safe default — most service misconfigs are exploitable
    # without valid credentials). Edit if this service authenticates first.
    return "N", "Au=None (default; edit for PostgreSQL)"


def infer_profile(directives: list[Directive]) -> SystemProfile:
    av, rationale_av = _infer_av(directives)
    au, rationale_au = _infer_au(directives)
    return SystemProfile(av=av, au=au, rationale_av=rationale_av, rationale_au=rationale_au)
