"""
plugins/docker/build_docker.py — GENERATED by `ccss plugin add`.

Defines the ground-truth ENTRIES for Docker. Mirrors the Apache /
Nginx build modules; run via `ccss build --target docker`.
"""

from __future__ import annotations

from config_assessment.plugins.apache_httpd.llm_pipeline import MisconfigEntry

_TARGET = "docker"

ENTRIES: list[MisconfigEntry] = [
    MisconfigEntry('docker group membership', 'untrusted users', 'trusted users only', '1.1.2', "", _TARGET),
    MisconfigEntry('container host hardening status', 'insecure', 'hardened', '1.2.1', "", _TARGET),
    MisconfigEntry("Docker daemon's cgroup usage", 'non-default', 'default', '2.11', "", _TARGET),
    MisconfigEntry('storage-opt dm.basesize', 'set', 'not set until needed', '2.12', "", _TARGET),
    MisconfigEntry('dockerd_log_driver', 'json', 'syslog', '2.14', "", _TARGET),
    MisconfigEntry('dockerd_no_new_privileges', 'not set', '--no-new-privileges', '2.15', "", _TARGET),
    MisconfigEntry('dockerd --live-restore', 'not present or not enabled', 'enabled', '2.16', "", _TARGET),
    MisconfigEntry('dockerd --userland-proxy', 'true', 'false', '2.17', "", _TARGET),
    MisconfigEntry('runtime parameter to the Docker daemon', '--experimental', '', '2.19', "", _TARGET),
    MisconfigEntry('icc', 'true', 'false', '2.2', "", _TARGET),
    MisconfigEntry('log-level', 'insecure', 'info', '2.3', "", _TARGET),
    MisconfigEntry('docker_insecure_registries', 'insecure', 'secure', '2.5', "", _TARGET),
    MisconfigEntry('docker storage driver', 'aufs', '', '2.6', "", _TARGET),
    MisconfigEntry('docker_storage_driver', 'devicemapper', '', '2.7', "", _TARGET),
    MisconfigEntry('tls', 'insecure', 'secure', '2.8', "", _TARGET),
    MisconfigEntry('dockerd --default-ulimit', '', '--default-ulimit nproc=1024:2048 --default-ulimit nofile=100:200', '2.9', "", _TARGET),
    MisconfigEntry('secrets_storage_in_dockerfiles', 'stored', 'not_stored', '4.10', "", _TARGET),
    MisconfigEntry('package_distribution_mechanism', 'insecure', 'secure', '4.11', "", _TARGET),
    MisconfigEntry('artifact_validation', 'insecure', 'secure', '4.12', "", _TARGET),
    MisconfigEntry('unnecessary_packages', '', 'minimal_base_image', '4.3', "", _TARGET),
    MisconfigEntry('image_update', 'not updated automatically', 'updated', '4.4', "", _TARGET),
    MisconfigEntry('DOCKER_CONTENT_TRUST', '0', '1', '4.5', "", _TARGET),
    MisconfigEntry('Dockerfile ADD instruction', 'ADD', 'COPY', '4.9', "", _TARGET),
    MisconfigEntry('swarm mode', '', 'disabled', '5.1', "", _TARGET),
    MisconfigEntry('--net', 'host', '', '5.10', "", _TARGET),
    MisconfigEntry('docker run --cpu-shares', 'not set or not specified', '<appropriate value based on container priority>', '5.12', "", _TARGET),
    MisconfigEntry('bind', '0.0.0.0', 'specific host interface', '5.14', "", _TARGET),
    MisconfigEntry('restart_policy', "not set or not 'on-failure:5'", "'on-failure:5'", '5.15', "", _TARGET),
    MisconfigEntry('docker_run_pid_host', 'present', 'absent', '5.16', "", _TARGET),
    MisconfigEntry('docker run command', '/dev/tty0:/dev/tty0:rwm -- device=/dev/temp_sda:/dev', '', '5.18', "", _TARGET),
    MisconfigEntry('ulimit', 'default (no override)', 'overridden as needed', '5.19', "", _TARGET),
    MisconfigEntry('docker run argument', '--uts=host', '', '5.21', "", _TARGET),
    MisconfigEntry('seccomp profile', 'disabled', 'enabled', '5.22', "", _TARGET),
    MisconfigEntry('docker exec --privileged', 'true', 'false', '5.23', "", _TARGET),
    MisconfigEntry('docker exec --user', 'root', '', '5.24', "", _TARGET),
    MisconfigEntry('docker run --cgroup-parent', 'present', 'absent', '5.25', "", _TARGET),
    MisconfigEntry('docker run options', 'insecure', '--rm -it --security-opt=no-new-privileges', '5.26', "", _TARGET),
    MisconfigEntry('Docker version pinning mechanism', 'latest', 'customized version pinning rules', '5.28', "", _TARGET),
    MisconfigEntry('--pids-limit', '0', '100 or greater', '5.29', "", _TARGET),
    MisconfigEntry('SELinux state', 'insecure', 'enabled', '5.3', "", _TARGET),
    MisconfigEntry('docker network create', 'docker0', '<user-defined-network>', '5.30', "", _TARGET),
    MisconfigEntry('docker run command', "'--userns=host'", '', '5.31', "", _TARGET),
    MisconfigEntry('docker_run_privileged', '--privileged', '', '5.5', "", _TARGET),
    MisconfigEntry('SSH daemon in container', 'running inside the container', 'not running inside the container', '5.7', "", _TARGET),
    MisconfigEntry('privileged_port_mapping', 'yes', 'no', '5.8', "", _TARGET),
    MisconfigEntry('Dockerfile EXPOSE instruction usage', '', '-p or --publish (explicitly define ports)', '5.9', "", _TARGET),
    MisconfigEntry('image_management', 'insecure_image_sprawl', 'controlled_image_management', '6.1', "", _TARGET),
    MisconfigEntry('docker container prune', '', 'periodically', '6.2', "", _TARGET),
    MisconfigEntry('number of manager nodes', 'excessive', 'only a single manager', '7.1', "", _TARGET),
    MisconfigEntry('--listen-addr', '', '<specific interface>', '7.2', "", _TARGET),
    MisconfigEntry('docker swarm overlay network flag', 'not --opt encrypted', '--opt encrypted', '7.3', "", _TARGET),
    MisconfigEntry('Docker secret management commands', '', 'follow docker secret documentation', '7.4', "", _TARGET),
    MisconfigEntry('swarm_manager_autolock', 'off', 'on', '7.5', "", _TARGET),
    MisconfigEntry('docker swarm auto-lock key rotation', 'not rotated', 'rotated', '7.6', "", _TARGET),
    MisconfigEntry('docker swarm update --cert-expiry', 'not set or expiry time less than 48h', '48h', '7.7', "", _TARGET),
    MisconfigEntry('docker swarm ca rotation', 'not rotated', 'rotated', '7.8', "", _TARGET),
    MisconfigEntry('Docker Swarm Data Plane and Management Plane Separation', 'default', '--advertise-addr=192.168.0.1 --data-path-addr=17.1.0.3', '7.9', "", _TARGET),
]
