"""
plugins/docker/parser.py — GENERATED by `ccss plugin add`.

Thin wrapper over the generic json parser. Edit only if this
target needs format-specific handling.
"""

from config_assessment.parsers.key_value import parse_file as parse_file  # re-export
