"""
plugins/docker/rules.py — GENERATED by `ccss plugin add`.

Deterministic SystemProfile inference. Edit the AV/Au logic for this service.
"""

from __future__ import annotations

from config_assessment.core.models import AuValue, AVValue, Directive, SystemProfile


# Absence rules: a directive that MUST be present/enabled. Flagged as a
# misconfiguration when missing from the scanned config (bad_value="").
ABSENCE_RULES: list[dict] = [
    {"directive": 'docker_daemon_authorization_plugin', "good_value": '<PLUGIN_ID>', "required_when": "always", "cis_section": '2.13'},
    {"directive": '--seccomp-profile', "good_value": '<custom_seccomp_profile>', "required_when": "always", "cis_section": '2.18'},
    {"directive": 'Docker Content Trust', "good_value": 'on', "required_when": "always", "cis_section": '4.2'},
    {"directive": 'HEALTHCHECK', "good_value": 'on', "required_when": "always", "cis_section": '4.6'},
    {"directive": 'docker run --ipc=host argument', "good_value": 'absent', "required_when": "always", "cis_section": '5.17'},
    {"directive": 'AppArmor_status', "good_value": 'enabled', "required_when": "always", "cis_section": '5.2'},
]


def _infer_av(directives: list[Directive]) -> tuple[AVValue, str]:
    return "N", "Network service (no bind directive declared)"


def _infer_au(directives: list[Directive]) -> tuple[AuValue, str]:
    # Default: Au=None (safe default — most service misconfigs are exploitable
    # without valid credentials). Edit if this service authenticates first.
    return "N", "Au=None (default; edit for Docker)"


def infer_profile(directives: list[Directive]) -> SystemProfile:
    av, rationale_av = _infer_av(directives)
    au, rationale_au = _infer_au(directives)
    return SystemProfile(av=av, au=au, rationale_av=rationale_av, rationale_au=rationale_au)
