"""
fix_dashboard_footer.py
------------------------
Torna o footer do dashboard dinâmico (deixa de dizer "Apache HTTP Server 2.4"
fixo em relatórios de outros targets como Nginx).

CORREÇÃO: troca a string literal do footer por uma f-string que usa
result.target_name. Mantém-se como string simples (sem parênteses) para
preservar a concatenação implícita com as strings adjacentes no return.

Uso:
    python3 fix_dashboard_footer.py
"""

from __future__ import annotations
import sys
from pathlib import Path

path = Path("core/report_dashboard.py")
if not path.exists():
    print("ERROR: core/report_dashboard.py not found. Run from ~/ccss_scan.")
    sys.exit(1)

content = path.read_text(encoding="utf-8")
original = content

if 'target: {_e(result.target_name)}' in content:
    print("\u2713 Footer already dynamic — skipping")
    sys.exit(0)

# Original: a plain string literal (part of implicit concatenation chain).
# Replace with an f-string literal (still a single string, no parentheses) so
# the implicit concatenation with the adjacent strings is preserved.
old = '"<div class=\\"footer\\">Generated by CCSS-Scan \\u00b7 NISTIR 7502 \\u00b7 CIS Apache HTTP Server 2.4 \\u00b7 offline report</div>\\n"'
new = 'f"<div class=\\"footer\\">Generated by CCSS-Scan \\u00b7 NISTIR 7502 \\u00b7 target: {_e(result.target_name)} \\u00b7 offline report</div>\\n"'

if old in content:
    content = content.replace(old, new, 1)
    print("\u2713 Footer now uses result.target_name (f-string, concatenation preserved)")
else:
    print("\u26a0 Could not find the footer line verbatim. Showing what's there:")
    for i, line in enumerate(content.splitlines(), 1):
        if "footer" in line and "Generated by" in line:
            print(f"  L{i}: {line.strip()}")
    sys.exit(1)

path.write_text(content, encoding="utf-8")

import ast
try:
    ast.parse(path.read_text(encoding="utf-8"))
    print("\nSyntax OK. Footer is now target-aware.")
except SyntaxError as e:
    print(f"\nFAIL line {e.lineno}: {e.msg} — restoring original")
    path.write_text(original, encoding="utf-8")
    sys.exit(1)
