"""
plugins/tomcat/__init__.py — GENERATED by `ccss plugin add`.

Edit this file to customise detection and metadata for Tomcat.
"""

from __future__ import annotations

from pathlib import Path

from config_assessment.core.models import Directive, SystemProfile, TargetMetadata
from config_assessment.core.runtime import register_plugin
from config_assessment.core.target import (
    Target,
    CONFIDENCE_EXACT_FILENAME,
    CONFIDENCE_SYNTAX_MARKER,
    CONFIDENCE_DIRECTORY,
)
from config_assessment.plugins.tomcat.parser import parse_file
from config_assessment.plugins.tomcat.rules import infer_profile

_FILENAMES = {'tomcat.conf'}


class TomcatPlugin(Target):
    """Tomcat target plugin (U Apache Tomcat Application Server 9 STIG V3R4 Manual-xccdf)."""

    def detect(self, path: str) -> bool:
        p = Path(path)
        if p.is_file():
            return p.name in _FILENAMES
        if p.is_dir():
            return any((p / fn).exists() for fn in _FILENAMES)
        return False

    def parse_config(self, path: str) -> list[Directive]:
        p = Path(path)
        if p.is_dir():
            for fn in _FILENAMES:
                entry = p / fn
                if entry.exists():
                    return parse_file(str(entry))
            return []
        return parse_file(path)

    def get_profile(self, directives: list[Directive]) -> SystemProfile:
        return infer_profile(directives)

    def metadata(self) -> TargetMetadata:
        return TargetMetadata(
            name="tomcat",
            display_name="Tomcat",
            version="1.0",
            benchmark_source="U Apache Tomcat Application Server 9 STIG V3R4 Manual-xccdf",
            priority=100,
            version_exposing_directives=(),
        )

    def detection_confidence(self, path: str) -> int:
        p = Path(path)
        if p.is_file() and p.name in _FILENAMES:
            return CONFIDENCE_EXACT_FILENAME
        if p.is_dir():
            return CONFIDENCE_DIRECTORY
        return 0


register_plugin(TomcatPlugin())
