"""
plugins/tomcat/build_tomcat.py — GENERATED by `ccss plugin add`.

Defines the ground-truth ENTRIES for Tomcat. Mirrors the Apache /
Nginx build modules; run via `ccss build --target tomcat`.
"""

from __future__ import annotations

from config_assessment.plugins.apache_httpd.llm_pipeline import MisconfigEntry

_TARGET = "tomcat"

ENTRIES: list[MisconfigEntry] = [
    MisconfigEntry('keystore password', 'changeit', 'secure_password', 'SV-222931r1137578_rule', "", _TARGET),
    MisconfigEntry('com.sun.management.jmxremote.ssl', 'false', 'true', 'SV-222964r1016511_rule', "", _TARGET),
    MisconfigEntry('connectionURL', 'ldap://localhost:389', 'ldaps://localhost:636', 'SV-222965r961029_rule', "", _TARGET),
    MisconfigEntry('FIPSMode', 'off', 'on', 'SV-222968r961050_rule', "", _TARGET),
    MisconfigEntry('secure', 'false', 'true', 'SV-222932r1137578_rule', "", _TARGET),
    MisconfigEntry('http-only', 'false', 'true', 'SV-222933r1137578_rule', "", _TARGET),
    MisconfigEntry('readonly', 'false', 'true', 'SV-222934r1137578_rule', "", _TARGET),
    MisconfigEntry('scheme', 'http', 'https', 'SV-222935r1137578_rule', "", _TARGET),
    MisconfigEntry('pattern', '', '%h %l %t %u "%r" %s %b', 'SV-222939r960894_rule', "", _TARGET),
    MisconfigEntry('pattern', '', '%h %l %t %u "%r" %s %b', 'SV-222940r960897_rule', "", _TARGET),
    MisconfigEntry('pattern', '', '%h %l %t %u "%r" %s %b', 'SV-222942r960897_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/logs permissions', '740', '750', 'SV-222943r960930_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/logs/* permissions', 'insecure_value (not 640)', '640', 'SV-222944r960930_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/conf/* file permissions', 'permissions other than 640', '640', 'SV-222945r960933_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/conf folder permissions', 'insecure_value (not 750)', '750', 'SV-222946r960933_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_HOME/bin/*jar permissions', 'not set to 640', '640', 'SV-222947r960936_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_HOME/bin permissions', 'not 750', '750', 'SV-222948r960939_rule', "", _TARGET),
    MisconfigEntry('UMask', 'insecure_value', '0027', 'SV-222949r960960_rule', "", _TARGET),
    MisconfigEntry('allowTrace', 'true', 'false', 'SV-222950r960963_rule', "", _TARGET),
    MisconfigEntry('port', 'any_value_other_than_-1', '-1', 'SV-222951r960963_rule', "", _TARGET),
    MisconfigEntry('deployXML', 'true', 'false', 'SV-222955r960963_rule', "", _TARGET),
    MisconfigEntry('privileged', 'true', 'false', 'SV-222961r1043177_rule', "", _TARGET),
    MisconfigEntry('com.sun.management.jmxremote.authenticate', 'false', 'true', 'SV-222963r960972_rule', "", _TARGET),
    MisconfigEntry('keystore_location', '', '/opt/tomcat/conf/<filename.jks>', 'SV-222967r985893_rule', "", _TARGET),
    MisconfigEntry('certificationVerification', 'false', 'true', 'SV-222971r1136930_rule', "", _TARGET),
    MisconfigEntry('showServerInfo', 'true', 'false', 'SV-222975r961167_rule', "", _TARGET),
    MisconfigEntry('showReport', 'true', 'false', 'SV-222977r961170_rule', "", _TARGET),
    MisconfigEntry('session-timeout', 'insecure_value', '600', 'SV-222979r1043182_rule', "", _TARGET),
    MisconfigEntry('failureCount', 'insecure_value', '5', 'SV-222981r961281_rule', "", _TARGET),
    MisconfigEntry('shell', '/bin/bash', '/usr/sbin/nologin', 'SV-222983r961353_rule', "", _TARGET),
    MisconfigEntry('USER', 'root', 'tomcat', 'SV-222984r961353_rule', "", _TARGET),
    MisconfigEntry('group', '', 'tomcat', 'SV-222987r961461_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/logs ownership', 'not owned by tomcat user', 'owned by tomcat user', 'SV-222988r961461_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/work ownership', '', 'tomcat:tomcat', 'SV-222991r961461_rule', "", _TARGET),
    MisconfigEntry('auth-method', 'insecure_value', 'CLIENT-CERT', 'SV-222993r985888_rule', "", _TARGET),
    MisconfigEntry('javax.net.ssl.trustStore', 'insecure_value', '/path/to/truststore', 'SV-222994r961596_rule', "", _TARGET),
    MisconfigEntry('org.apache.catalina.connector.CoyoteAdapter.ALLOW_BACKSLASH', 'true', 'false', 'SV-223004r1135506_rule', "", _TARGET),
    MisconfigEntry('org.apache.catalina.connector.Response.ENFORCE_ENCODING_IN_GET_WRITER', 'insecure_value', 'true', 'SV-223005r1135509_rule', "", _TARGET),
    MisconfigEntry('action_mail_acct', 'root', '<email_address>', 'SV-223010r985887_rule', "", _TARGET),
    MisconfigEntry('hstsEnabled', 'false', 'true', 'SV-222928r960762_rule', "", _TARGET),
    MisconfigEntry('pattern', '', '%s', 'SV-222941r960897_rule', "", _TARGET),
    MisconfigEntry('debug', 'insecure_value', '0', 'SV-222953r960963_rule', "", _TARGET),
    MisconfigEntry('listings', 'true', 'false', 'SV-222954r960963_rule', "", _TARGET),
    MisconfigEntry('xpoweredBy', 'true', 'false', 'SV-222957r960963_rule', "", _TARGET),
    MisconfigEntry('org.apache.catalina.connector. RECYCLE_FACADES', 'insecure_value', 'true', 'SV-222973r1043180_rule', "", _TARGET),
    MisconfigEntry('401.jsp content', 'insecure_value (sample passwords and user accounts)', 'secure_value (generic error information that assists users but does not provide sample data to users)', 'SV-222976r961170_rule', "", _TARGET),
    MisconfigEntry('lockOutTime', 'insecure_value', '600', 'SV-222982r961281_rule', "", _TARGET),
    MisconfigEntry('pattern', '', '%h %l %t %u "%r" %s %b', 'SV-222985r961362_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/temp/ owner', 'insecure_user', 'tomcat', 'SV-222989r961461_rule', "", _TARGET),
    MisconfigEntry('$CATALINA_BASE/temp permissions', 'less than 750', '750', 'SV-222990r961461_rule', "", _TARGET),
    MisconfigEntry('javax.net.ssl.trustStore', '', '/path/to/truststore', 'SV-223001r1137585_rule', "", _TARGET),
    MisconfigEntry('org.apache.catalina.STRICT_SERVLET_COMPLIANCE', 'false', 'true', 'SV-223002r961863_rule', "", _TARGET),
    MisconfigEntry('org.apache.catalina.connector.RECYCLE_FACADES', 'false', 'true', 'SV-223003r1135503_rule', "", _TARGET),
]
