"""
plugins/tomcat/rules.py — GENERATED by `ccss plugin add`.

Deterministic SystemProfile inference. Edit the AV/Au logic for this service.
"""

from __future__ import annotations

from config_assessment.core.models import AuValue, AVValue, Directive, SystemProfile


# Absence rules: a directive that MUST be present/enabled. Flagged as a
# misconfiguration when missing from the scanned config (bad_value="").
ABSENCE_RULES: list[dict] = [
    {"directive": 'Valve', "good_value": '<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" prefix="appl", suffix=".txt" pattern="%h %l %t %u &quot;%r&quot; %s %b" />', "required_when": "always", "cis_section": 'SV-222930r960765_rule'},
    {"directive": 'internalProxies', "good_value": '[172.16.0.10|172.16.0.11]', "required_when": "always", "cis_section": 'SV-222937r960879_rule'},
    {"directive": 'Valve', "good_value": '<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" prefix="localhost_access_log" suffix=".txt" pattern="%h %l %t %u "%r" %s %b" />', "required_when": "always", "cis_section": 'SV-222938r960882_rule'},
    {"directive": 'name', "good_value": 'secure_value', "required_when": "always", "cis_section": 'SV-222952r1135497_rule'},
    {"directive": 'autoDeploy', "good_value": 'false', "required_when": "always", "cis_section": 'SV-222956r960963_rule'},
    {"directive": 'className', "good_value": 'JNDIRealm', "required_when": "always", "cis_section": 'SV-222962r1051118_rule'},
    {"directive": 'com.sun.management.jmxremote.host', "good_value": '192.168.0.150', "required_when": "always", "cis_section": 'SV-222969r1137579_rule'},
    {"directive": 'RemoteAddrValve', "good_value": 'secure_value', "required_when": "always", "cis_section": 'SV-222970r1137579_rule'},
    {"directive": 'Membership className', "good_value": 'McastService or Static', "required_when": "always", "cis_section": 'SV-222974r961122_rule'},
    {"directive": 'LockOutRealm', "good_value": '<Realm className="org.apache.catalina.realm.LockOutRealm" failureCount="5" lockOutTime="600">', "required_when": "always", "cis_section": 'SV-222980r961278_rule'},
    {"directive": '$CATALINA_HOME ownership', "good_value": 'owned by root user and group tomcat', "required_when": "always", "cis_section": 'SV-222986r961461_rule'},
    {"directive": 'Cluster', "good_value": 'secure_value', "required_when": "always", "cis_section": 'SV-222995r961620_rule'},
    {"directive": 'Tomcat version', "good_value": '<latest secure version of Tomcat>', "required_when": "always", "cis_section": 'SV-222996r1067548_rule'},
    {"directive": 'className', "good_value": 'org.apache.catalina.valves.AccessLogValve', "required_when": "always", "cis_section": 'SV-222997r1016518_rule'},
    {"directive": '$CATALINA_HOME/bin -p wa -k tomcat', "good_value": '-w $CATALINA_HOME/bin -p wa -k tomcat', "required_when": "always", "cis_section": 'SV-222998r1193096_rule'},
    {"directive": '$CATALINA_BASE/conf -p wa -k tomcat', "good_value": 'present', "required_when": "always", "cis_section": 'SV-222999r1193098_rule'},
    {"directive": '$CATALINA_HOME/lib -w', "good_value": '-w $CATALINA_HOME/lib -p wa -k tomcat', "required_when": "always", "cis_section": 'SV-223000r1193100_rule'},
    {"directive": 'Tomcat users with management roles', "good_value": 'ISSO_approved_users', "required_when": "always", "cis_section": 'SV-223006r961863_rule'},
    {"directive": 'maxActiveSessions', "good_value": '', "required_when": "always", "cis_section": 'SV-222926r960735_rule'},
    {"directive": '$CATALINA_BASE', "good_value": '$CATALINA_BASE/webapps/examples', "required_when": "always", "cis_section": 'SV-222958r960963_rule'},
    {"directive": 'webapps', "good_value": '$CATALINA_BASE/webapps/ROOT', "required_when": "always", "cis_section": 'SV-222959r960963_rule'},
    {"directive": '$CATALINA_BASE', "good_value": '', "required_when": "always", "cis_section": 'SV-222960r960963_rule'},
    {"directive": 'connector', "good_value": '', "required_when": "always", "cis_section": 'SV-223008r961863_rule'},
    {"directive": 'address', "good_value": 'SSP_approved_IP_address', "required_when": "always", "cis_section": 'SV-223009r961863_rule'},
]


def _infer_av(directives: list[Directive]) -> tuple[AVValue, str]:
    return "N", "Network service (no bind directive declared)"


def _infer_au(directives: list[Directive]) -> tuple[AuValue, str]:
    # Default: Au=None (safe default — most service misconfigs are exploitable
    # without valid credentials). Edit if this service authenticates first.
    return "N", "Au=None (default; edit for Tomcat)"


def infer_profile(directives: list[Directive]) -> SystemProfile:
    av, rationale_av = _infer_av(directives)
    au, rationale_au = _infer_au(directives)
    return SystemProfile(av=av, au=au, rationale_av=rationale_av, rationale_au=rationale_au)
