"""
plugins/mysql/build_mysql.py — GENERATED by `ccss plugin add`.

Defines the ground-truth ENTRIES for MySQL. Mirrors the Apache /
Nginx build modules; run via `ccss build --target mysql`.
"""

from __future__ import annotations

from config_assessment.plugins.apache_httpd.llm_pipeline import MisconfigEntry

_TARGET = "mysql"

ENTRIES: list[MisconfigEntry] = [
    MisconfigEntry('ssl_cipher', '*', 'ECDHE-ECDSA-AES128-GCM-SHA256', '2.10', "", _TARGET),
    MisconfigEntry('plugin-load', '', 'validate_password.so', '2.6', "", _TARGET),
    MisconfigEntry('block_encryption_mode', 'aes-128-ecb', 'aes-256-cbc', '2.7', "", _TARGET),
    MisconfigEntry('bind_address', '*', '192.0.2.24', '2.9', "", _TARGET),
    MisconfigEntry('allow-suspicious-udfs', 'ON', 'OFF', '4.3', "", _TARGET),
    MisconfigEntry('local_infile', 'ON', 'OFF', '4.4', "", _TARGET),
    MisconfigEntry('skip-grant-tables', 'TRUE', 'FALSE', '4.5', "", _TARGET),
    MisconfigEntry('skip-symbolic-links', 'NO', 'YES', '4.6', "", _TARGET),
    MisconfigEntry('secure_file_priv', '', '/path/to/safe/directory', '4.8', "", _TARGET),
    MisconfigEntry('sql_mode', 'NO_ENGINE_SUBSTITUTION', 'STRICT_ALL_TABLES,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION', '4.9', "", _TARGET),
    MisconfigEntry('log_error', '', '/path/to/error/log', '6.1', "", _TARGET),
    MisconfigEntry('audit_log', '', 'FORCE_PLUS_PERMANENT', '6.11', "", _TARGET),
    MisconfigEntry('log-bin', '/var/log/mysql/bin-log.*|/usr/local/mysql/data/bin-log.*|/', '/non-system-partition/path/to/binary-logs', '6.2', "", _TARGET),
    MisconfigEntry('log-warnings', '1', '2', '6.3', "", _TARGET),
    MisconfigEntry('log-raw', 'ON', 'OFF', '6.4', "", _TARGET),
    MisconfigEntry('audit_log_connection_policy', 'NONE', 'ERRORS|ALL', '6.5', "", _TARGET),
    MisconfigEntry('audit_log_exclude_accounts', '', 'NULL', '6.6', "", _TARGET),
    MisconfigEntry('audit_log_include_accounts', '', 'NULL', '6.7', "", _TARGET),
    MisconfigEntry('old_passwords', '1', '0', '7.1', "", _TARGET),
    MisconfigEntry('secure_auth', 'OFF', 'ON', '7.2', "", _TARGET),
    MisconfigEntry('sql_mode', 'NO_ENGINE_SUBSTITUTION', 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION', '7.4', "", _TARGET),
    MisconfigEntry('have_ssl', 'NO', 'YES', '8.1', "", _TARGET),
    MisconfigEntry('ssl_type', '', 'ANY,X509,SPECIFIED', '8.2', "", _TARGET),
    MisconfigEntry('master_info_repository', 'FILE', 'TABLE', '9.3', "", _TARGET),
]
